version: '3.3'

services:
  web:
    restart: always
    container_name: jobir_uz
    build: .
    env_file:
      - .env
  
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: jobir_uz_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/src/app/static
    ports:
      - 8081:80
    depends_on:
      - web