# Generated by Django 5.0 on 2024-09-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="images/projects")),
                ("link", models.URLField()),
                ("position", models.IntegerField()),
                (
                    "status",
                    models.BooleanField(
                        choices=[(True, "Active"), (False, "Inactive")], default=True
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
