# Generated by Django 5.0 on 2024-09-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
